name: aurum_music
description: Aurum Music - Premium Gold Music Experience
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  audio_service: ^0.18.13
  audio_session: ^0.1.18
  provider: ^6.1.1
  http: ^1.1.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  palette_generator: ^0.3.3+3
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  rxdart: ^0.27.7
  uuid: ^4.3.3
  url_launcher: ^6.3.0
  permission_handler: ^11.0.0
  on_audio_query: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
