name: Generate Keystore
on:
  workflow_dispatch:
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Generate keystore
        run: |
          keytool -genkey -v -keystore aurum-release.jks \
            -alias aurum -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass aurum1234 -keypass aurum1234 \
            -dname "CN=Aurum,OU=Dev,O=Aurum,L=IN,S=IN,C=IN"
          echo "====START===="
          base64 -w 0 aurum-release.jks
          echo ""
          echo "====END===="
